version: "3.9" 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  prometheus:
    image: prom/prometheus
  grafana: 
    image: grafana/grafana

networks:
  default:
    # network
